## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [6]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


'1.18.1'

## Concatenando Arrays

In [2]:
array1 = np.ones(4) # Array1 com array preenchido apenas de "1"

In [3]:
array2 = np.arange(15) # Array2 com array de 15 posições (0 a 14)

In [4]:
array_conc = np.concatenate((array1, array2)) # Função de concatenação

In [5]:
array_conc #19 elementos dentro do objeto array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

## Joining Arrays

In [6]:
a = np.ones((3,3)) 
b = np.zeros((3,3)) 

In [7]:
print(a) #Primeiro array ones

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(b) #Segundo array zeros

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
?np.vstack #Função que empilha em sequência vertical

In [10]:
?np.hstack #Função que empilha em sequência horizontal

In [11]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [13]:
# Joining arrays - colchetes por ser uma LISTA de numéros
a = np.array([0, 1, 2]) #Lista de números usa colchetes
b = np.array([3, 4, 5]) #Lista de números usa colchetes
c = np.array([6, 7, 8]) #Lista de números usa colchetes

In [14]:
?np.column_stack # Empilha um array 1D como colunas em um array 2D

In [15]:
?np.row_stack # Empilha um array 1D como linhas em um array 2D

In [16]:
np.column_stack((a, b, c)) # Arrays agrupados verticalmente como colunas

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [17]:
np.row_stack((a, b, c)) # Arrays agrupados horizontalmente como linhas

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Split Arrays

In [16]:
#Função np.arange() para criar array de 16 elementos (0,15)
#Função np.reshape() para transformar  o array 1D em 2D (4x4)
array3 = np.arange(16).reshape(4,4) 
array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
#Função np.hsplit para divisão horizontal do array3 anterior
#np.hsplit(nome do array, quantidade de 2 partes)
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [20]:
array3_p1 #Primeira saída

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
array3_p2 #Segunda saída 

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [22]:
#Função np.vsplit para divisão horizontal do array3 anterior
#np.vsplit(nome do array, quantidade de 2 partes)
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [23]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Gravando e Carragendo Dados com NumPy

In [25]:
dados = array3 # Criar objeto dados a partir do array3

In [26]:
# Função np.save() do pacote numpy salva o array
# np.saca("nome do objeto para salvar no SO", nome do objeto a gravar)
# Arquivo será salvo no mesmo diretório do Jupyter Notebook
np.save('dados_saved_v1', dados)

In [27]:
# Função np.load("nome do objeto no SO")
loaded_data = np.load('dados_saved_v1.npy')

In [28]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])